name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install ssh keys
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Build and copy files
        run: |
            docker build . -t huds/rsoi-webapp
            docker save -o rsoi-webapp.tar huds/rsoi-webapp
            scp rsoi-webapp.tar docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~
      - name: Start application
        run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker load -i rsoi-webapp.tar; docker compose up -d"
      - name: Cleanup
        run: rm -rf ~/.ssh



      # TODO build, test and deploy project

      # - name: Run API Tests
      #   uses: matt-ball/newman-action@master
      #   with:
      #     collection: postman/[inst] Lab1.postman_collection.json
      #     environment: postman/[inst][heroku] Lab1.postman_environment.json
      #     delayRequest: 100
      #     reporters: '[ "cli" ]'

      # - name: Autograding
      #   uses: education/autograding@v1
      #   continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 1
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"
